name: tests

on:
    push:
        branches:
            - '**'

concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

jobs:
    tests:
        runs-on: ${{ matrix.os }}
        strategy:
            fail-fast: false
            matrix:
                os: [macos-latest, ubuntu-latest, windows-latest]
        steps:
            - uses: actions/checkout@v4.1.7
            - uses: actions/setup-node@v4.0.3
            - name: run test
              shell: bash
              run: |
                  npm ci
                  npm run docs
